<?php

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function competency_file_help($route_name, RouteMatchInterface $route_match){
  switch ($route_name) {
    case 'help.page.competency_file':
      $output = '';
      $output .= '<h3>'.t('About').'</h3>';
      $output .= '<p>'.t('Please send help').'</p>';

      return $output;
  }
}




//https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Core%21Entity%21entity.api.php/function/hook_entity_create/8.2.x
//hook_ENTITY_TYPE_create()


